# Generated by Django 5.1.7 on 2025-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name'], 'verbose_name': 'Раса', 'verbose_name_plural': 'Расы'},
        ),
        migrations.AddField(
            model_name='race',
            name='race_slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
