# Generated by Django 5.1.7 on 2025-05-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='npc_picks/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'НПС',
                'verbose_name_plural': 'НПСи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='location_picks/')),
                ('name', models.CharField(max_length=60)),
                ('small_description', models.TextField(blank=True, null=True, verbose_name='Маленькое описание для карточки Без гиперссылок')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Unknown', 'Неизвестен'), ('Martial_law', 'Военное положение'), ('Captured', 'Захвачен'), ('Resistance', 'Сопротивление'), ('Neutral', 'Нейтральный'), ('Destroyed', 'Уничтожен'), ('Capital', 'Столица'), ('Liberal', 'Либеральный'), ('Conservative', 'Консервативный'), ('Racist', 'Расистский')], max_length=50, null=True)),
                ('population', models.CharField(blank=True, choices=[('NO', 'Нет'), ('Unknown', 'Неизвестна'), ('Humans', 'Люди'), ('S_elfs', 'Высшие эльфы'), ('Gnoms', 'Гномы'), ('Dwarfs', 'Дварфы'), ('Half_height', 'Полурослки'), ('Demons', 'Демоны'), ('Drou', 'Дроу'), ('Goblins', 'Гоблины'), ('Vampires', 'Вампиры'), ('Giffs', 'Гифы'), ('Forers_Elfs', 'Лесные эльфы')], max_length=50, null=True)),
                ('what_adventures', models.ManyToManyField(blank=True, to='adventures.dndadventure', verbose_name='В каких приключениях принимал участие')),
                ('npcs', models.ManyToManyField(blank=True, to='map.npc', verbose_name='Ключевые NPC')),
            ],
            options={
                'verbose_name': 'Абстрактная модель(не трогай)',
                'verbose_name_plural': 'Абстрактная модель(не трогай)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.location')),
                ('glava', models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.npc', verbose_name='Мэр')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
            bases=('map.location',),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.location')),
                ('capital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cap_of', to='map.city', verbose_name='Столица')),
                ('glava', models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.npc', verbose_name='Правитель')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
            bases=('map.location',),
        ),
        migrations.AddField(
            model_name='city',
            name='Land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='map.country'),
        ),
        migrations.CreateModel(
            name='Vilage',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.location')),
                ('Land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='map.country')),
                ('glava', models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.npc', verbose_name='Представитель')),
            ],
            options={
                'verbose_name': 'Деревня',
                'verbose_name_plural': 'Деревни',
            },
            bases=('map.location',),
        ),
    ]
