# Generated by Django 5.1.7 on 2025-05-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0003_npc_alter_heromodel_know_npc'),
        ('adventures', '0003_alter_dndadventure_npcs'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='glava',
            field=models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hero.npc', verbose_name='Правитель'),
        ),
        migrations.AlterField(
            model_name='vilage',
            name='glava',
            field=models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hero.npc', verbose_name='Представитель'),
        ),
        migrations.AlterField(
            model_name='city',
            name='glava',
            field=models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hero.npc', verbose_name='Мэр'),
        ),
        migrations.AlterField(
            model_name='location',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='Hero.npc', verbose_name='Ключевые NPC'),
        ),
        migrations.DeleteModel(
            name='NPC',
        ),
    ]
