# Generated by Django 5.1.7 on 2025-03-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_m',
            name='slug',
            field=models.SlugField(default='lol65', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
