# Generated by Django 5.1.7 on 2025-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_hero_m_slug_alter_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_m',
            name='description',
            field=models.TextField(default='kapusta1'),
            preserve_default=False,
        ),
    ]
