# Generated by Django 5.1.7 on 2025-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_hero_m_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Land',
            field=models.CharField(choices=[('COUNTRY', 'Страна'), ('CITY', 'Город'), ('VILLAGE', 'Деревня')], default='None', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
