# Generated by Django 5.1.2 on 2025-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_location_land_country_alter_location_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='population',
            field=models.CharField(default='Неизвестно', max_length=50),
            preserve_default=False,
        ),
    ]
