# Generated by Django 5.1.2 on 2025-03-10 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_city_land_alter_vilage_land_dnd_adventure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnd_adventure',
            name='heroes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dnd_adventure',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='map.npc'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='adventures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.dnd_adventure', verbose_name='what_adventure'),
        ),
    ]
