# Generated by Django 5.1.2 on 2025-03-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_dnd_adventure_heroes_alter_dnd_adventure_npcs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='npsc',
            new_name='npcs',
        ),
    ]
