# Generated by Django 5.1.2 on 2025-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_rename_npsc_location_npcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RemoveField(
            model_name='hero_m',
            name='adventures',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='adventures',
        ),
        migrations.AddField(
            model_name='hero_m',
            name='adventures',
            field=models.ManyToManyField(to='map.dnd_adventure', verbose_name='adventures'),
        ),
        migrations.AddField(
            model_name='npc',
            name='adventures',
            field=models.ManyToManyField(to='map.dnd_adventure', verbose_name='adventures'),
        ),
    ]
