# Generated by Django 5.1.2 on 2025-03-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_npc_slug_remove_hero_m_adventures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cap_of', to='map.city', verbose_name='capital'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='location_picks/'),
        ),
        migrations.AddField(
            model_name='npc',
            name='image',
            field=models.ImageField(null=True, upload_to='npc_picks/'),
        ),
    ]
