# Generated by Django 5.1.2 on 2025-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_country_capital_location_image_npc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(choices=[('NO', 'Нет'), ('Unknown', 'Неизвестна'), ('Humans', 'Люди'), ('S_elfs', 'Высшие эльфы'), ('Gnoms', 'Гномы'), ('Dwarfs', 'Дварфы'), ('Half_height', 'Полурослки'), ('Demons', 'Демоны'), ('Drou', 'Дроу'), ('Goblins', 'Гоблины'), ('Vampires', 'Вампиры'), ('Giffs', 'Гифы')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Unknown', 'Неизвестен'), ('Martial_law', 'Военное положение'), ('Captured', 'Захвачен'), ('Resistance', 'Сопротивление'), ('Neutral', 'Нейтральный'), ('Destroyed', 'Уничтожен'), ('Capital', 'Столица'), ('Liberal', 'Либеральный'), ('Conservative', 'Консервативный'), ('Racist', 'Расистский')], max_length=50, null=True),
        ),
    ]
