# Generated by Django 5.1.2 on 2025-03-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_city_mer_country_head_of_state_vilage_predstavitel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='dnd_adventure',
            options={'verbose_name': 'Приключение', 'verbose_name_plural': 'Приключения'},
        ),
        migrations.AlterModelOptions(
            name='hero_m',
            options={'verbose_name': 'Герой', 'verbose_name_plural': 'Герои'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Абстрактная модель(не трогай)', 'verbose_name_plural': 'Абстрактная модель(не трогай)'},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'verbose_name': 'НПС', 'verbose_name_plural': 'НПСи'},
        ),
        migrations.AlterModelOptions(
            name='vilage',
            options={'verbose_name': 'Деревня', 'verbose_name_plural': 'Деревни'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение(пока не трогай)', 'verbose_name_plural': 'Песещения(пока не трогай)'},
        ),
        migrations.RemoveField(
            model_name='npc',
            name='adventures',
        ),
        migrations.AlterField(
            model_name='city',
            name='mer',
            field=models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.npc', verbose_name='Мэр'),
        ),
        migrations.AlterField(
            model_name='country',
            name='head_of_state',
            field=models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.npc', verbose_name='Правитель'),
        ),
        migrations.AlterField(
            model_name='hero_m',
            name='adventures',
            field=models.ManyToManyField(blank=True, to='map.dnd_adventure', verbose_name='adventures'),
        ),
        migrations.AlterField(
            model_name='hero_m',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hero_m',
            name='image',
            field=models.ImageField(blank=True, upload_to='hero_picks/'),
        ),
        migrations.AlterField(
            model_name='hero_m',
            name='visited_cities',
            field=models.ManyToManyField(blank=True, through='map.Visit', to='map.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='map.npc', verbose_name='Кто здесь бывал'),
        ),
        migrations.AlterField(
            model_name='vilage',
            name='predstavitel',
            field=models.OneToOneField(blank=True, default='Неизвестно', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.npc', verbose_name='Представитель'),
        ),
    ]
