# Generated by Django 5.1.2 on 2025-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='what_adventures',
            field=models.ManyToManyField(blank=True, to='map.dnd_adventure', verbose_name='В каких приключения был'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='image',
            field=models.ImageField(blank=True, upload_to='npc_picks/'),
        ),
    ]
