# Generated by Django 5.1.2 on 2025-03-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_location_what_adventures_alter_npc_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='mer',
            new_name='glava',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='head_of_state',
            new_name='glava',
        ),
        migrations.RenameField(
            model_name='vilage',
            old_name='predstavitel',
            new_name='glava',
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cap_of', to='map.city', verbose_name='Столица'),
        ),
    ]
