# Generated by Django 5.1.2 on 2025-03-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_rename_mer_city_glava_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero_m',
            name='email',
        ),
    ]
