# Generated by Django 5.1.2 on 2025-03-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_remove_hero_m_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnd_adventure',
            options={'ordering': ['name'], 'verbose_name': 'Приключение', 'verbose_name_plural': 'Приключения'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Абстрактная модель(не трогай)', 'verbose_name_plural': 'Абстрактная модель(не трогай)'},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['name'], 'verbose_name': 'НПС', 'verbose_name_plural': 'НПСи'},
        ),
        migrations.AddField(
            model_name='dnd_adventure',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер приключения'),
        ),
        migrations.AlterField(
            model_name='dnd_adventure',
            name='description',
            field=models.TextField(verbose_name='Описание приключения'),
        ),
        migrations.AlterField(
            model_name='dnd_adventure',
            name='heroes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Учавствовашие герои'),
        ),
        migrations.AlterField(
            model_name='dnd_adventure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название приключения'),
        ),
        migrations.AlterField(
            model_name='dnd_adventure',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='map.npc', verbose_name='Учавствовавшие NPCи'),
        ),
        migrations.AlterField(
            model_name='hero_m',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='map.npc', verbose_name='Ключевые NPC'),
        ),
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(choices=[('NO', 'Нет'), ('Unknown', 'Неизвестна'), ('Humans', 'Люди'), ('S_elfs', 'Высшие эльфы'), ('Gnoms', 'Гномы'), ('Dwarfs', 'Дварфы'), ('Half_height', 'Полурослки'), ('Demons', 'Демоны'), ('Drou', 'Дроу'), ('Goblins', 'Гоблины'), ('Vampires', 'Вампиры'), ('Giffs', 'Гифы'), ('Forers_Elfs', 'Лесные эльфы')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='what_adventures',
            field=models.ManyToManyField(blank=True, to='map.dnd_adventure', verbose_name='В каких приключениях принимал участие'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
