# Generated by Django 5.1.2 on 2025-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_alter_dnd_adventure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnd_adventure',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dnd_adventure',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True, verbose_name='Номер приключения'),
        ),
    ]
