# Generated by Django 5.1.7 on 2025-03-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_alter_visit_options_remove_hero_m_adventures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_m',
            name='know_npc',
            field=models.ManyToManyField(to='map.npc', verbose_name='Каких нпс знает'),
        ),
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(blank=True, choices=[('NO', 'Нет'), ('Unknown', 'Неизвестна'), ('Humans', 'Люди'), ('S_elfs', 'Высшие эльфы'), ('Gnoms', 'Гномы'), ('Dwarfs', 'Дварфы'), ('Half_height', 'Полурослки'), ('Demons', 'Демоны'), ('Drou', 'Дроу'), ('Goblins', 'Гоблины'), ('Vampires', 'Вампиры'), ('Giffs', 'Гифы'), ('Forers_Elfs', 'Лесные эльфы')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='small_description',
            field=models.TextField(blank=True, null=True, verbose_name='Маленькое описание для карточки Без гиперссылок'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(blank=True, choices=[('Unknown', 'Неизвестен'), ('Martial_law', 'Военное положение'), ('Captured', 'Захвачен'), ('Resistance', 'Сопротивление'), ('Neutral', 'Нейтральный'), ('Destroyed', 'Уничтожен'), ('Capital', 'Столица'), ('Liberal', 'Либеральный'), ('Conservative', 'Консервативный'), ('Racist', 'Расистский')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vilage',
            name='Land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='map.country'),
        ),
    ]
