# Generated by Django 5.1.2 on 2025-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_hero_m_know_npc_alter_location_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero_m',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
