# Generated by Django 5.1.7 on 2025-05-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_hero_m_email'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='populationn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.race', verbose_name='Преобладающая расса'),
        ),
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
