# Generated by Django 5.1.7 on 2025-05-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_location_populationn_alter_location_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='population',
        ),
    ]
