# Generated by Django 5.1.7 on 2025-05-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_remove_location_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='populationn',
            new_name='population',
        ),
    ]
