# Generated by Django 5.1.7 on 2025-05-01 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_rename_populationn_location_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.dnd_adventure'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
