# Generated by Django 5.1.7 on 2025-05-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_visit_visited_alter_visit_visited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visited_at',
        ),
    ]
