# Generated by Django 5.1.7 on 2025-10-19 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DndAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название приключения')),
                ('number', models.DecimalField(blank=True, decimal_places=1, max_digits=1000, null=True, verbose_name='Номер приключения')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Описание приключения')),
                ('heroes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Учавствовашие герои')),
                ('npcs', models.ManyToManyField(blank=True, to='Hero.npc', verbose_name='Учавствовавшие NPCи')),
            ],
            options={
                'verbose_name': 'Приключение',
                'verbose_name_plural': 'Приключения',
                'ordering': ['number'],
            },
        ),
    ]
