# Generated by Django 5.1.7 on 2025-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndadventure',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='map.npc', verbose_name='Учавствовавшие NPCи'),
        ),
    ]
