# Generated by Django 5.1.7 on 2025-10-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndadventure',
            name='image',
            field=models.ImageField(blank=True, upload_to='adventure_avatars/'),
        ),
    ]
