# Generated by Django 5.1.7 on 2025-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0003_npc_alter_heromodel_know_npc'),
        ('adventures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndadventure',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='Hero.npc', verbose_name='Учавствовавшие NPCи'),
        ),
    ]
