# Generated by Django 5.1.7 on 2025-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={},
        ),
        migrations.AlterModelTable(
            name='hero',
            table='Heroes_table',
        ),
    ]
