# Generated by Django 5.1.7 on 2025-03-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0002_alter_hero_options_alter_hero_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
