# Generated by Django 5.1.7 on 2025-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='npc_picks/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'НПС',
                'verbose_name_plural': 'НПСи',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='know_npc',
            field=models.ManyToManyField(to='Hero.npc', verbose_name='Каких нпс знает'),
        ),
    ]
